# Generated by Django 3.1.6 on 2021-03-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impOrder', '0003_auto_20210310_1534'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordertransaction',
            table='impOrderTransaction',
        ),
    ]
