# Generated by Django 3.1.6 on 2021-03-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210303_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PAYMENT_PROGRESS', '결제 진행'), ('PAYMENT_COMPLETION', '결제 완료'), ('PAYMENT_ERROR', '결제 오류'), ('PAYMENT_ FAILED', '결제 실패'), ('PREPARE', '배송 준비'), ('SHIPPING', '배송 중'), ('SHIPPED', '배송 완료')], default='PAYMENT_PROGRESS', max_length=20),
        ),
    ]
